DROP TABLE districtes;
DROP TABLE barris;
DROP TABLE wifi;
DROP TABLE wifi_madre;

CREATE TABLE wifi_madre(
    CODI_CAPA VARCHAR(255),
    CAPA_GENERICA VARCHAR(255),
    NOM_CAPA VARCHAR(255),
    ED50_COORD_X DECIMAL(11,4),
    ED50_COORD_Y DECIMAL(11,4),
    ETRS89_COORD_X DECIMAL(11,4),
    ETRS89_COORD_Y DECIMAL(11,4),
    LONGITUD DECIMAL(11,4),
    LATITUD DECIMAL(11,4),
    EQUIPAMENT VARCHAR(255),
    DISTRICTE INT,
    BARRI INT,
    NOM_DISTRICTE VARCHAR(255),
    NOM_BARRI VARCHAR(255),
    ADRECA VARCHAR(255),
    TELEFON    VARCHAR(255)
    );    

COPY wifi_madre (CODI_CAPA,CAPA_GENERICA,NOM_CAPA,ED50_COORD_X,ED50_COORD_Y,ETRS89_COORD_X,ETRS89_COORD_Y,LONGITUD,LATITUD,EQUIPAMENT,DISTRICTE,BARRI,NOM_DISTRICTE,NOM_BARRI,ADRECA,TELEFON) 
FROM '/home/oc-admin/Descargas/PUNTS_WIFI.csv' delimiter ',' csv header;    

CREATE TABLE wifi(
    ID_WIFI INT GENERATED ALWAYS AS IDENTITY,PRIMARY KEY,
    CODI_CAPA VARCHAR(255),
    CAPA_GENERICA VARCHAR(255),
    NOM_CAPA VARCHAR(255),
    ED50_COORD_X DECIMAL(11,4),
    ED50_COORD_Y DECIMAL(11,4),
    ETRS89_COORD_X DECIMAL(11,4),
    ETRS89_COORD_Y DECIMAL(11,4),
    LONGITUD DECIMAL(11,4),
    LATITUD DECIMAL(11,4),
    EQUIPAMENT VARCHAR(255),
    BARRI INT,
    ADRECA VARCHAR(255),
    TELEFON    VARCHAR(255)
    );    
    
CREATE TABLE districtes(
    IdDistricte INT PRIMARY KEY,
    Nom_Districte VARCHAR(255)
    );

CREATE TABLE barris(
    IdBarri INT, 
    IdDistricte INT,fk iddistricte(districtes) 
    Nom_Barri VARCHAR(255)
    );

DECLARE
		IMPORT_BARRIS CURSOR FOR
		SELECT DISTINCT(BARRI),NOM_BARRI
			FROM PUNTS_WIFI
			GROUP BY BARRI, NOM_BARRI
			ORDER BY BARRI ASC;
	
	v_barri     PUNTS_WIFI.BARRI%TYPE;
	v_n_barri   PUNTS_WIFI.NOM_BARRI%TYPE;
	
BEGIN
	OPEN IMPORT_BARRIS ;
	LOOP
		FETCH IMPORT_BARRIS  INTO v_barri,v_n_barri;
		INSERT INTO barris(Barri,Nom_Barri)
			VALUES (v_barri,v_n_barri);
		--EXIT WHEN IMPORT_BARRIS%NOTFOUND;	
	END LOOP;
	CLOSE IMPORT_BARRIS ;
	COMMIT;
END; 